test deploy

diff --git a/JenkinsDeployfile b/JenkinsDeployfile
--- a/JenkinsDeployfile
+++ b/JenkinsDeployfile
@@ -36,16 +36,18 @@ pipeline {
 	}
 	stage('TEST app'){
 		steps {
-		echo "Check - is the app running!"
-		sh """
-		RESULT=`curl -is http://13.201.164.185:81/ | head -1 | awk '{print $2}'`
-		if test $RESULT -eq 200; then
-		  echo "We're Good! Result is $RESULT - OK!"
-		else
-		  echo "ERROR: $RESULT"
-		  exit 1
-		fi
-		"""
+			script {
+			echo "Check - is the app running!"
+			sh """
+			RESULT=`curl -is http://13.201.164.185:81/ | head -1 | awk '{print $2}'`
+			if test $RESULT -eq 200; then
+		  		echo "We're Good! Result is $RESULT - OK!"
+			else
+		  		echo "ERROR: $RESULT"
+		  	exit 1
+			fi
+			"""
+		}
 		}
 	}
     }
